CI: Split Flatpak beta and stable publishing jobs
We currently publish the same build from the same branch
to Flathub. However, soon we'll need to build the Flatpak
manifest in different branches, and publish them in different
repositories.

Prepare for that by splitting the publish step in two: one
for Flathub, and another for Flathub Beta. Because GitHub
does not support YAML anchoring, slightly rearrange these
two publish steps to have the exact same steps, and only
change env variables.

Sorry, I wish there was a cleaner way to do this.

diff --git a/.github/workflows/flatpak.yml b/.github/workflows/flatpak.yml
--- a/.github/workflows/flatpak.yml
+++ b/.github/workflows/flatpak.yml
@@ -58,12 +58,14 @@ jobs:
           manifest-path: CI/flatpak/com.obsproject.Studio.json
           cache-key: flatpak-builder-${{ github.sha }}
 
-  publish:
-    name: Publish to Flathub
+  publish_beta:
+    name: Publish to Flathub Beta
     runs-on: [ubuntu-latest]
     if: github.event_name == 'release'
     env:
       FLATPAK_BUILD_PATH: flatpak_app/files/share
+      FLATHUB_REPOSITORY: beta
+      FLATHUB_TOKEN: ${{ secrets.FLATHUB_BETA_TOKEN }}
     container:
       image: bilelmoussaoui/flatpak-github-actions:kde-5.15-21.08
       options: --privileged
@@ -98,17 +100,60 @@ jobs:
         run: |
           ostree commit --repo=repo --canonical-permissions --branch=screenshots/x86_64 flatpak_app/screenshots
 
-      - name: Publish to Flathub Beta
+      - name: Publish
         uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
         with:
           flat-manager-url: https://hub.flathub.org/
-          repository: beta
-          token: ${{ secrets.FLATHUB_BETA_TOKEN }}
+          repository: ${{ env.FLATHUB_REPOSITORY }}
+          token: ${{ env.FLATHUB_TOKEN }}
 
-      - name: Publish to Flathub
+  # GitHub Actions does not support YAML anchors. This is a carbon-copy of the
+  # 'publish_beta' job. Please keep the steps of both jobs in sync.
+  publish_stable:
+    name: Publish to Flathub Beta
+    runs-on: [ubuntu-latest]
+    if: "github.event_name == 'release' && !contains(github.ref, '-beta') && !contains(github.ref, '-rc')"
+    env:
+      FLATPAK_BUILD_PATH: flatpak_app/files/share
+      FLATHUB_REPOSITORY: stable
+      FLATHUB_TOKEN: ${{ secrets.FLATHUB_TOKEN }}
+    container:
+      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-21.08
+      options: --privileged
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2.3.3
+        with:
+          submodules: 'recursive'
+
+      - name: Build Flatpak Manifest
+        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@master
+        with:
+          bundle: obs-studio-${{ github.sha }}.flatpak
+          manifest-path: CI/flatpak/com.obsproject.Studio.json
+          cache-key: flatpak-builder-${{ github.sha }}
+          mirror-screenshots-url: https://dl.flathub.org/repo/screenshots
+
+      - name: Validate AppStream
+        shell: bash
+        working-directory: ${{ env.FLATPAK_BUILD_PATH }}
+        run: |
+          appstream-util validate appdata/com.obsproject.Studio.appdata.xml
+
+      - name: Verify icon and metadata in app-info
+        shell: bash
+        working-directory: ${{ env.FLATPAK_BUILD_PATH }}
+        run: |
+          test -f app-info/icons/flatpak/128x128/com.obsproject.Studio.png || { echo "Missing 128x128 icon in app-info" ; exit 1; }
+          test -f app-info/xmls/com.obsproject.Studio.xml.gz || { echo "Missing com.obsproject.Studio.xml.gz in app-info" ; exit 1; }
+
+      - name: Commit screenshots to the OSTree repository
+        run: |
+          ostree commit --repo=repo --canonical-permissions --branch=screenshots/x86_64 flatpak_app/screenshots
+
+      - name: Publish
         uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
-        if: "!contains(github.ref, '-beta') && !contains(github.ref, '-rc')"
         with:
           flat-manager-url: https://hub.flathub.org/
-          repository: stable
-          token: ${{ secrets.FLATHUB_TOKEN }}
+          repository: ${{ env.FLATHUB_REPOSITORY }}
+          token: ${{ env.FLATHUB_TOKEN }}
